spring:
  datasource:
    password: SuxtiFNQW5
    url: jdbc:mysql://localhost:8081/todappdb
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
      show-sql: true
